// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_-boiqUA9Nb2yTEjDK0faik4P2oUHu-Q',
    appId: '1:446782805524:web:08d78da12a4d0655a63901',
    messagingSenderId: '446782805524',
    projectId: 'notificaiton-example',
    authDomain: 'notificaiton-example.firebaseapp.com',
    storageBucket: 'notificaiton-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8csogOBhmvW5GlYCM1Nw9nSZb8l6eqOY',
    appId: '1:446782805524:android:0929ddf4b52708b9a63901',
    messagingSenderId: '446782805524',
    projectId: 'notificaiton-example',
    storageBucket: 'notificaiton-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0-C9VWQOkNwhzygbUURBVKc7rxKyjIc',
    appId: '1:446782805524:ios:3b99e205ed450de3a63901',
    messagingSenderId: '446782805524',
    projectId: 'notificaiton-example',
    storageBucket: 'notificaiton-example.appspot.com',
    iosBundleId: 'com.example.notificationMapTdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA0-C9VWQOkNwhzygbUURBVKc7rxKyjIc',
    appId: '1:446782805524:ios:3b99e205ed450de3a63901',
    messagingSenderId: '446782805524',
    projectId: 'notificaiton-example',
    storageBucket: 'notificaiton-example.appspot.com',
    iosBundleId: 'com.example.notificationMapTdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_-boiqUA9Nb2yTEjDK0faik4P2oUHu-Q',
    appId: '1:446782805524:web:bc4b75f03d979c98a63901',
    messagingSenderId: '446782805524',
    projectId: 'notificaiton-example',
    authDomain: 'notificaiton-example.firebaseapp.com',
    storageBucket: 'notificaiton-example.appspot.com',
  );
}
